// Backup of original Landing.jsx
// This file was autogenerated by the Task-04 backup step.
// If you need to restore the original landing page, rename this file to Landing.jsx

import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  Sparkles, Cpu, Bot, Code2, ShieldCheck, Globe, Rocket, Brain,
  ArrowRight, PlayCircle, Download, MapPin, Star, GraduationCap, Trophy, Atom,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import ParticleBg from "@/components/ParticleBg";
import NeuralNet from "@/components/NeuralNet";
import GalleryGrid from "@/components/GalleryGrid";
import CourseCard from "@/components/CourseCard";
import api from "@/lib/api";

const HERO_IMG = "https://static.prod-images.emergentagent.com/jobs/daa89962-3eb5-4a90-9a28-c4a18ef03946/images/f7c5843cae54e6d0b564298906b915e5f6de90ce68c7bf1c0d0c94b65897b41c.png";
const ROBOTICS_IMG = "https://static.prod-images.emergentagent.com/jobs/daa89962-3eb5-4a90-9a28-c4a18ef03946/images/97e40991d6971a5fc37e5550971f929eb6e5c71ff29769d8e7ac7744f683294f.png";
const AI_GLOBE = "https://static.prod-images.emergentagent.com/jobs/daa89962-3eb5-4a90-9a28-c4a18ef03946/images/cd76c1ba5685629be8766293f62450538b472162ae494a00b71dc965689dfd11.png";
const CIRCUIT_IMG = "https://images.unsplash.com/photo-1631375937044-6dd5beac01d2?w=1200";

function Counter({ value, label, suffix = "", icon: Icon }) {
  const [n, setN] = useState(0);
  useEffect(() => {
    const start = performance.now();
    const dur = 1400;
    let raf;
    const tick = (t) => {
      const p = Math.min((t - start) / dur, 1);
      setN(Math.floor(p * value));
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [value]);
  return (
    <div className="glass rounded-2xl p-5 md:p-6">
      <div className="flex items-center gap-2 text-primary mb-2">
        <Icon className="h-4 w-4" />
        <span className="font-mono text-[10px] tracking-[0.25em] uppercase">{label}</span>
      </div>
      <div className="font-display text-3xl md:text-4xl font-extrabold cyan-gold-text">
        {n.toLocaleString()}{suffix}
      </div>
    </div>
  );
}

const FEATURES = [
  { icon: Brain, title: "AI-Powered Learning", desc: "Personalized roadmaps & smart recommendations." },
  { icon: Bot, title: "Robotics Labs", desc: "Hands-on with Arduino, Raspberry Pi & ROS 2." },
  { icon: Code2, title: "Live Coding Studios", desc: "Pair-programming and weekly hackathons." },
  { icon: ShieldCheck, title: "Cybersecurity Range", desc: "CTF-style challenges & labs." },
];

export default function LandingBackup() {
  const [stats, setStats] = useState({ students: 12000, courses: 80, teachers: 60, countries: 18 });
  const [courses, setCourses] = useState([]);
  const [blogs, setBlogs] = useState([]);
  const [gallery, setGallery] = useState([]);
  const [news, setNews] = useState([]);

  useEffect(() => {
    api.get("/stats").then((r) => setStats(r.data)).catch(() => {});
    api.get("/courses").then((r) => setCourses(r.data.slice(0, 6))).catch(() => {});
    api.get("/blogs?limit=3").then((r) => setBlogs(r.data)).catch(() => {});
    api.get("/gallery?limit=6").then((r) => setGallery(r.data.slice(0, 6))).catch(() => {});
    api.get("/news?limit=3").then((r) => setNews(r.data)).catch(() => {});
  }, []);

  return (
    <div>
      <h1>This is a backup copy of the original Landing.jsx</h1>
      <p>Restore by renaming this file to Landing.jsx</p>
    </div>
  );
}
